create table if not exists account_chart_tree(
set_id integer not null,
account_id integer null,
tree_effective_date varchar(255) null,
tree_code integer null,
tree_description varchar(255) null,
level1 varchar(255) null,
level1_desc varchar(255) null,
level2 varchar(255) null,
level2_desc varchar(255) null,
level3 varchar(255) null,
level3_desc varchar(255) null,
level4 varchar(255) null,
level4_desc varchar(255) null,
level5 varchar(255) null,
level5_desc varchar(255) null,
level6 varchar(255) null,
level6_desc varchar(255) null,
level7 varchar(255) null,
level7_desc varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint account_chart_tree_pk primary key(set_id));